### ISSUE TITLE
Crash - Invalid save file crashes Yodine

### ISSUE THREAD

**Issue by Aralicia** [Dude112113/Yodine#9]
**Issue**
The following save.yaml crashes Yodine when loaded.
This is due to the coordinates of the lamp being non-numerical

**Save File**
```
---
networks:
- &network_0
  extensions:
    fields:
      LampRange: 1
      ButtonStyle: 0
      ButtonOnStateValue: 1
      LampColorSaturation: 1
      ButtonOffStateValue: 0
      LampOn: 0
      LampColorHue: 0
      LampColorValue: 1
      LampLumens: 600
    color:
    - 0.003921568627451
    - 0.93333333333333
    - 0.22352941176471
  remark: No Remark.
  name: network_0
  devices:
  - !lamp
    LampRange: LampRange
    LampColorSaturation: LampColorSaturation
    extensions:
      y: y
      x: x
    LampLumens: LampLumens
    LampOn: LampOn
    LampColorValue: LampColorValue
    LampColorHue: LampColorHue
relays: []
...
```

**Error Dump**

> Error
> 
> devices/init.lua:53: x is not a number
> 
> 
> Traceback
> 
> [C]: in function 'assert'
> devices/init.lua:53: in function 'create'
> devices/init.lua:90: in function 'deserialize'
> Network.lua:80: in function 'deserialize'
> Map.lua:29: in function 'deserialize'
> SaveSystem.lua:112: in function 'load'
> menus/SavesMenu.lua:51: in function 'onclick'
> libs/loveframes/objects/button.lua:162: in function 'mousereleased'
> libs/loveframes/objects/frame.lua:628: in function 'mousereleased'
> libs/loveframes/objects/base.lua:144: in function 'mousereleased'
> libs/loveframes/init.lua:245: in function 'mousereleased'
> main.lua:244: in function <main.lua:243>
> [C]: in function 'xpcall'
